// 1. build utils functions:
//      - get user by id
//      - get recipe by id
//       -get all recipes

//* convert the all async component to custom hooks components and re-usable
//* BUILD REDCUERS FUNCTIONS- get etc..

const recipe = {
  id: "some-id",
  owner: "userid",
  isShared: false,
  level: 3, // out of 3 probably
  type: "italian",
  ingrediants: ["pasta", "tomato", "olive"],
  dishImg: "",
  recipeImg: "",
  time: 0,
  name: "",
};
const user = {
  name: "",
  lastName: "",
  level: " begginer / su-chef / chef ",
  email: "",
  img: "profile-pic",
  city: "",
  country: "",
};
