// 1. build utils functions:
//      - get user by id
//      - get recipe by id
//       -get all recipes

// 2. state handling schem

// 3. Make a components tree describe events and data relations (component-wide, behind the scenes state storage)

// 4. create reccipe form and settings

const recipe = {
  id: "some-id",
  owner: "userid",
  isShared: false,
  level: 3, // out of 5 probably
  type: "italian",
  ingrediants: ["pasta", "tomato", "olive"],
};
